### ISSUE TITLE
Any way to exit early and leave batch processing running in background...

### ISSUE THREAD

**Issue by tfrancois** [sergelerator/async-batch#16]
I run an Express app in NodeJS that leverages PapaParser and it works very similar to this excellent tool - in that it seamlessly spawns async operations to worker threads without issue.  It works just as it says.  Here is my problem.

With PapaPaser, I am able to initiate a large file import and "exit early" and return a response back to the calling party from Express.  The import process and follow-up tasks that PP knows about and configured to run in sequence continue without issue until completion.  I would very much love to have this util work the same way.  Right now, no matter what I've tried, it won't allow me to resolve the promise and allow Express to send a response while the process continues in the background.  BUT here's what's interesting - when I run my long-running job from Postman and the response times out - the task still continues running!  So I'm guessing there must be a way to avoid the response timeout problem and still let the task continue in the background like PP.

Is this possible?  Right now, either the API task times out with no response code to the caller OR if the job completes before the timeout, the response is returned normally from which I can return the results to the caller.

One other tidbit, if it's a short task, the current behavior should remain.  So I think the author should perhaps have an option to "exit early" or turn off/leave off the exit early feature and keep the status quo.  Any suggestions?

Thanks in the meantime for a nifty tool - it otherwise works great!

**Comment by sergelerator** [comment]
Hey @tfrancois thanks for the feedback. I'm not sure I get the whole context of your issue, but here are some thoughts:

- HTTP API servers like the one you describe, built with Express, are not ideal for handling long running jobs in general, I recommend you look into a background task processor instead.
- The response timeout is often times not defined in your Express application, but instead in another layer, this could be an nginx server in front of your Express server, or even the client application itself (e.g. Postman, the browser, etc.) You cannot control this, and this is yet another reason to avoid running long processing tasks in an HTTP server handler.

Adding the feature you're asking for would break the current API, now you need to take into account the possibility of not having resolved values for a portion of your tasks. This would decrease the stability and predictability of `asyncBatch`, which I wouldn't want to introduce into a tool that others already rely on.
