### ISSUE TITLE
In some condition same task is executed multiple time

### ISSUE THREAD

**Issue by Aravin** [sergelerator/async-batch#8]
In some condition the same task is executed multiple time.

Say for example. I have 6000 items and passing them to asyncBatch with batch size 100.

Somewhere around 70+ async call - the same data is getting executed again.

It keeps increasing gradually as the batch goes on.

I don't have any other input that this.

Any idea guys?

**Comment by sergelerator** [comment]
Sorry for the very late response, are you still having this issue? If you could provide a minimal reproduction I'd be glad to help debug and fix the issue.

**Comment by Aravin** [comment]
npm uninstall async-batch and wrote own.

Thanks for the reply @sergelerator
